### ISSUE TITLE
Errores ortográficos

### ISSUE THREAD

**Issue by ematiasm** [prodezzargenta/about-cryptocurrencies#1]
Error ortográfico en sobre-las-criptomonedas.pdf 
página 361
autencididad = autenticidad
dumento = documento

"Un esquema matemático para demostrar la `autencididad` de
un mensaje digital o `dumento`. Es una huella virtual que es única a
una persona y es usada para identificar a los firmantes y asegurar
los datos en los documentos digitales. [...]

**Comment by prodezzargenta** [comment]
Listo! Ya está corregida la línea 5703. Muchas gracias!
